eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

microservices:
  payment-service:
    endpoints:
      endpoint:
        url: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        url: http://ORDER-SERVICE/order/bookOrder
